/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: PlayerId;
    battingOrder: bigint;
    name: string;
    isBowler: boolean;
}
export type WicketType = {
    __kind__: "LBW";
    LBW: null;
} | {
    __kind__: "HitWicket";
    HitWicket: null;
} | {
    __kind__: "RunOut";
    RunOut: null;
} | {
    __kind__: "Stumped";
    Stumped: null;
} | {
    __kind__: "Bowled";
    Bowled: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Caught";
    Caught: null;
};
export interface BallByBallRecord {
    ballNumber: BallNumber;
    batsmanId: PlayerId;
    wicket?: WicketType;
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    overNumber: OverNumber;
    isFreeHit: boolean;
    bowlerId: PlayerId;
}
export interface Toss {
    choice: TossChoice;
    winnerTeamId: TeamId;
}
export interface Match {
    id: MatchId;
    isFinished: boolean;
    deliveries: Array<BallByBallRecord>;
    toss: Toss;
    winner?: TeamId;
    teamAId: TeamId;
    teamBId: TeamId;
    innings: Array<Innings>;
    currentInnings: bigint;
    rules: MatchRules;
}
export type MatchId = bigint;
export type TeamId = bigint;
export type PlayerId = bigint;
export type InningsId = bigint;
export type BallNumber = bigint;
export interface Delivery {
    batsmanId: PlayerId;
    wicket?: WicketType;
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    isFreeHit: boolean;
    isBye: boolean;
    isLegBye: boolean;
    bowlerId: PlayerId;
}
export interface MatchRules {
    freeHitEnabled: boolean;
    duckworthLewisTarget?: bigint;
    maxOversPerBowler: bigint;
    oversLimit: bigint;
    powerplayOvers: Array<bigint>;
}
export interface Innings {
    id: bigint;
    bowlingTeamId: TeamId;
    deliveries: Array<Delivery>;
    overs: bigint;
    completed: boolean;
    totalRuns: bigint;
    wicketsLost: bigint;
    battingTeamId: TeamId;
}
export interface TournamentRules {
    teamReadinessPenaltyOvers: bigint;
    widesNoBallBowlerChangeThreshold: bigint;
    finalMatches: bigint;
    defaultPenaltyRuns: bigint;
    leaguePowerplayOvers: bigint;
    totalMatches: bigint;
    slowOverRatePenaltyRuns: bigint;
    maxOversBowlerShortFormat: bigint;
    leagueOvers: bigint;
    freeHitApplicable: boolean;
    lbwApplicable: boolean;
    finalOvers: bigint;
    inningsDurationMinutes: bigint;
    maxBallsPerBatsmanShortFormat: bigint;
    knockoutMatches: bigint;
    finalPowerplayOvers: bigint;
    maxFieldersOutside30Yards: bigint;
    maxOversBowlerLongFormat: bigint;
    bouncerLimitPerOver: bigint;
    teamReadinessPenaltyMinutes: bigint;
    numTeams: bigint;
    semifinalMatches: bigint;
    leagueMatches: bigint;
    timeoutDurationSeconds: bigint;
    maxBallsPerBatsmanLongFormat: bigint;
}
export type OverNumber = bigint;
export interface Team {
    id: TeamId;
    logo: string;
    name: string;
    color: string;
    squad: Array<PlayerId>;
    players: Array<Player>;
}
export enum TossChoice {
    Bat = "Bat",
    Bowl = "Bowl"
}
export interface backendInterface {
    addPlayer(teamId: TeamId, name: string, battingOrder: bigint, isBowler: boolean): Promise<PlayerId>;
    addTeam(name: string, color: string, logo: string): Promise<TeamId>;
    createMatch(teamAId: TeamId, teamBId: TeamId, rules: MatchRules, toss: Toss): Promise<MatchId>;
    getAllTeams(): Promise<Array<Team>>;
    getDeliveriesByInnings(matchId: MatchId, inningsId: InningsId): Promise<Array<Delivery>>;
    getMatch(matchId: MatchId): Promise<Match | null>;
    getPlayerStats(teamId: TeamId, playerId: PlayerId): Promise<Player | null>;
    getTeam(teamId: TeamId): Promise<Team | null>;
    getTournamentRules(): Promise<TournamentRules>;
    recordDelivery(matchId: MatchId, inningsId: InningsId, delivery: Delivery): Promise<void>;
    resetAllData(): Promise<void>;
    selectSquad(teamId: TeamId, squad: Array<PlayerId>): Promise<void>;
    updateMatchRules(matchId: MatchId, newRules: MatchRules): Promise<void>;
    updateTournamentRules(rules: TournamentRules): Promise<void>;
}
import type { BallByBallRecord as _BallByBallRecord, BallNumber as _BallNumber, Delivery as _Delivery, Innings as _Innings, Match as _Match, MatchId as _MatchId, MatchRules as _MatchRules, OverNumber as _OverNumber, Player as _Player, PlayerId as _PlayerId, Team as _Team, TeamId as _TeamId, Toss as _Toss, TossChoice as _TossChoice, WicketType as _WicketType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPlayer(arg0: TeamId, arg1: string, arg2: bigint, arg3: boolean): Promise<PlayerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTeam(arg0: string, arg1: string, arg2: string): Promise<TeamId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0, arg1, arg2);
            return result;
        }
    }
    async createMatch(arg0: TeamId, arg1: TeamId, arg2: MatchRules, arg3: Toss): Promise<MatchId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, to_candid_MatchRules_n1(this._uploadFile, this._downloadFile, arg2), to_candid_Toss_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, to_candid_MatchRules_n1(this._uploadFile, this._downloadFile, arg2), to_candid_Toss_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAllTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return result;
        }
    }
    async getDeliveriesByInnings(arg0: MatchId, arg1: InningsId): Promise<Array<Delivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveriesByInnings(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveriesByInnings(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: MatchId): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerStats(arg0: TeamId, arg1: PlayerId): Promise<Player | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStats(arg0, arg1);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStats(arg0, arg1);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeam(arg0: TeamId): Promise<Team | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentRules(): Promise<TournamentRules> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentRules();
            return result;
        }
    }
    async recordDelivery(arg0: MatchId, arg1: InningsId, arg2: Delivery): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDelivery(arg0, arg1, to_candid_Delivery_n32(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDelivery(arg0, arg1, to_candid_Delivery_n32(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async resetAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllData();
            return result;
        }
    }
    async selectSquad(arg0: TeamId, arg1: Array<PlayerId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectSquad(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectSquad(arg0, arg1);
            return result;
        }
    }
    async updateMatchRules(arg0: MatchId, arg1: MatchRules): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatchRules(arg0, to_candid_MatchRules_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatchRules(arg0, to_candid_MatchRules_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTournamentRules(arg0: TournamentRules): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentRules(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentRules(arg0);
            return result;
        }
    }
}
function from_candid_BallByBallRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BallByBallRecord): BallByBallRecord {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Delivery_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Delivery): Delivery {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Innings_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Innings): Innings {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MatchRules_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchRules): MatchRules {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TossChoice_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TossChoice): TossChoice {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Toss_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Toss): Toss {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_WicketType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WicketType): WicketType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WicketType]): WicketType | null {
    return value.length === 0 ? null : from_candid_WicketType_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : from_candid_Match_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamId]): TeamId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    isFinished: boolean;
    deliveries: Array<_BallByBallRecord>;
    toss: _Toss;
    winner: [] | [_TeamId];
    teamAId: _TeamId;
    teamBId: _TeamId;
    innings: Array<_Innings>;
    currentInnings: bigint;
    rules: _MatchRules;
}): {
    id: MatchId;
    isFinished: boolean;
    deliveries: Array<BallByBallRecord>;
    toss: Toss;
    winner?: TeamId;
    teamAId: TeamId;
    teamBId: TeamId;
    innings: Array<Innings>;
    currentInnings: bigint;
    rules: MatchRules;
} {
    return {
        id: value.id,
        isFinished: value.isFinished,
        deliveries: from_candid_vec_n16(_uploadFile, _downloadFile, value.deliveries),
        toss: from_candid_Toss_n19(_uploadFile, _downloadFile, value.toss),
        winner: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.winner)),
        teamAId: value.teamAId,
        teamBId: value.teamBId,
        innings: from_candid_vec_n24(_uploadFile, _downloadFile, value.innings),
        currentInnings: value.currentInnings,
        rules: from_candid_MatchRules_n27(_uploadFile, _downloadFile, value.rules)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ballNumber: _BallNumber;
    batsmanId: _PlayerId;
    wicket: [] | [_WicketType];
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    overNumber: _OverNumber;
    isFreeHit: boolean;
    bowlerId: _PlayerId;
}): {
    ballNumber: BallNumber;
    batsmanId: PlayerId;
    wicket?: WicketType;
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    overNumber: OverNumber;
    isFreeHit: boolean;
    bowlerId: PlayerId;
} {
    return {
        ballNumber: value.ballNumber,
        batsmanId: value.batsmanId,
        wicket: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.wicket)),
        runs: value.runs,
        isNoBall: value.isNoBall,
        isWide: value.isWide,
        overNumber: value.overNumber,
        isFreeHit: value.isFreeHit,
        bowlerId: value.bowlerId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    choice: _TossChoice;
    winnerTeamId: _TeamId;
}): {
    choice: TossChoice;
    winnerTeamId: TeamId;
} {
    return {
        choice: from_candid_TossChoice_n21(_uploadFile, _downloadFile, value.choice),
        winnerTeamId: value.winnerTeamId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bowlingTeamId: _TeamId;
    deliveries: Array<_Delivery>;
    overs: bigint;
    completed: boolean;
    totalRuns: bigint;
    wicketsLost: bigint;
    battingTeamId: _TeamId;
}): {
    id: bigint;
    bowlingTeamId: TeamId;
    deliveries: Array<Delivery>;
    overs: bigint;
    completed: boolean;
    totalRuns: bigint;
    wicketsLost: bigint;
    battingTeamId: TeamId;
} {
    return {
        id: value.id,
        bowlingTeamId: value.bowlingTeamId,
        deliveries: from_candid_vec_n7(_uploadFile, _downloadFile, value.deliveries),
        overs: value.overs,
        completed: value.completed,
        totalRuns: value.totalRuns,
        wicketsLost: value.wicketsLost,
        battingTeamId: value.battingTeamId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freeHitEnabled: boolean;
    duckworthLewisTarget: [] | [bigint];
    maxOversPerBowler: bigint;
    oversLimit: bigint;
    powerplayOvers: Array<bigint>;
}): {
    freeHitEnabled: boolean;
    duckworthLewisTarget?: bigint;
    maxOversPerBowler: bigint;
    oversLimit: bigint;
    powerplayOvers: Array<bigint>;
} {
    return {
        freeHitEnabled: value.freeHitEnabled,
        duckworthLewisTarget: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.duckworthLewisTarget)),
        maxOversPerBowler: value.maxOversPerBowler,
        oversLimit: value.oversLimit,
        powerplayOvers: value.powerplayOvers
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    batsmanId: _PlayerId;
    wicket: [] | [_WicketType];
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    isFreeHit: boolean;
    isBye: boolean;
    isLegBye: boolean;
    bowlerId: _PlayerId;
}): {
    batsmanId: PlayerId;
    wicket?: WicketType;
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    isFreeHit: boolean;
    isBye: boolean;
    isLegBye: boolean;
    bowlerId: PlayerId;
} {
    return {
        batsmanId: value.batsmanId,
        wicket: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.wicket)),
        runs: value.runs,
        isNoBall: value.isNoBall,
        isWide: value.isWide,
        isFreeHit: value.isFreeHit,
        isBye: value.isBye,
        isLegBye: value.isLegBye,
        bowlerId: value.bowlerId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LBW: null;
} | {
    HitWicket: null;
} | {
    RunOut: null;
} | {
    Stumped: null;
} | {
    Bowled: null;
} | {
    Other: string;
} | {
    Caught: null;
}): {
    __kind__: "LBW";
    LBW: null;
} | {
    __kind__: "HitWicket";
    HitWicket: null;
} | {
    __kind__: "RunOut";
    RunOut: null;
} | {
    __kind__: "Stumped";
    Stumped: null;
} | {
    __kind__: "Bowled";
    Bowled: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Caught";
    Caught: null;
} {
    return "LBW" in value ? {
        __kind__: "LBW",
        LBW: value.LBW
    } : "HitWicket" in value ? {
        __kind__: "HitWicket",
        HitWicket: value.HitWicket
    } : "RunOut" in value ? {
        __kind__: "RunOut",
        RunOut: value.RunOut
    } : "Stumped" in value ? {
        __kind__: "Stumped",
        Stumped: value.Stumped
    } : "Bowled" in value ? {
        __kind__: "Bowled",
        Bowled: value.Bowled
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "Caught" in value ? {
        __kind__: "Caught",
        Caught: value.Caught
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bat: null;
} | {
    Bowl: null;
}): TossChoice {
    return "Bat" in value ? TossChoice.Bat : "Bowl" in value ? TossChoice.Bowl : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BallByBallRecord>): Array<BallByBallRecord> {
    return value.map((x)=>from_candid_BallByBallRecord_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Innings>): Array<Innings> {
    return value.map((x)=>from_candid_Innings_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Delivery>): Array<Delivery> {
    return value.map((x)=>from_candid_Delivery_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Delivery_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Delivery): _Delivery {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_MatchRules_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchRules): _MatchRules {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TossChoice_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TossChoice): _TossChoice {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Toss_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Toss): _Toss {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_WicketType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WicketType): _WicketType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freeHitEnabled: boolean;
    duckworthLewisTarget?: bigint;
    maxOversPerBowler: bigint;
    oversLimit: bigint;
    powerplayOvers: Array<bigint>;
}): {
    freeHitEnabled: boolean;
    duckworthLewisTarget: [] | [bigint];
    maxOversPerBowler: bigint;
    oversLimit: bigint;
    powerplayOvers: Array<bigint>;
} {
    return {
        freeHitEnabled: value.freeHitEnabled,
        duckworthLewisTarget: value.duckworthLewisTarget ? candid_some(value.duckworthLewisTarget) : candid_none(),
        maxOversPerBowler: value.maxOversPerBowler,
        oversLimit: value.oversLimit,
        powerplayOvers: value.powerplayOvers
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    batsmanId: PlayerId;
    wicket?: WicketType;
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    isFreeHit: boolean;
    isBye: boolean;
    isLegBye: boolean;
    bowlerId: PlayerId;
}): {
    batsmanId: _PlayerId;
    wicket: [] | [_WicketType];
    runs: bigint;
    isNoBall: boolean;
    isWide: boolean;
    isFreeHit: boolean;
    isBye: boolean;
    isLegBye: boolean;
    bowlerId: _PlayerId;
} {
    return {
        batsmanId: value.batsmanId,
        wicket: value.wicket ? candid_some(to_candid_WicketType_n34(_uploadFile, _downloadFile, value.wicket)) : candid_none(),
        runs: value.runs,
        isNoBall: value.isNoBall,
        isWide: value.isWide,
        isFreeHit: value.isFreeHit,
        isBye: value.isBye,
        isLegBye: value.isLegBye,
        bowlerId: value.bowlerId
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    choice: TossChoice;
    winnerTeamId: TeamId;
}): {
    choice: _TossChoice;
    winnerTeamId: _TeamId;
} {
    return {
        choice: to_candid_TossChoice_n5(_uploadFile, _downloadFile, value.choice),
        winnerTeamId: value.winnerTeamId
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "LBW";
    LBW: null;
} | {
    __kind__: "HitWicket";
    HitWicket: null;
} | {
    __kind__: "RunOut";
    RunOut: null;
} | {
    __kind__: "Stumped";
    Stumped: null;
} | {
    __kind__: "Bowled";
    Bowled: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Caught";
    Caught: null;
}): {
    LBW: null;
} | {
    HitWicket: null;
} | {
    RunOut: null;
} | {
    Stumped: null;
} | {
    Bowled: null;
} | {
    Other: string;
} | {
    Caught: null;
} {
    return value.__kind__ === "LBW" ? {
        LBW: value.LBW
    } : value.__kind__ === "HitWicket" ? {
        HitWicket: value.HitWicket
    } : value.__kind__ === "RunOut" ? {
        RunOut: value.RunOut
    } : value.__kind__ === "Stumped" ? {
        Stumped: value.Stumped
    } : value.__kind__ === "Bowled" ? {
        Bowled: value.Bowled
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value.__kind__ === "Caught" ? {
        Caught: value.Caught
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TossChoice): {
    Bat: null;
} | {
    Bowl: null;
} {
    return value == TossChoice.Bat ? {
        Bat: null
    } : value == TossChoice.Bowl ? {
        Bowl: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
