/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TeamId = IDL.Nat;
export const PlayerId = IDL.Nat;
export const MatchRules = IDL.Record({
  'freeHitEnabled' : IDL.Bool,
  'duckworthLewisTarget' : IDL.Opt(IDL.Nat),
  'maxOversPerBowler' : IDL.Nat,
  'oversLimit' : IDL.Nat,
  'powerplayOvers' : IDL.Vec(IDL.Nat),
});
export const TossChoice = IDL.Variant({ 'Bat' : IDL.Null, 'Bowl' : IDL.Null });
export const Toss = IDL.Record({
  'choice' : TossChoice,
  'winnerTeamId' : TeamId,
});
export const MatchId = IDL.Nat;
export const Player = IDL.Record({
  'id' : PlayerId,
  'battingOrder' : IDL.Nat,
  'name' : IDL.Text,
  'isBowler' : IDL.Bool,
});
export const Team = IDL.Record({
  'id' : TeamId,
  'logo' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'squad' : IDL.Vec(PlayerId),
  'players' : IDL.Vec(Player),
});
export const InningsId = IDL.Nat;
export const WicketType = IDL.Variant({
  'LBW' : IDL.Null,
  'HitWicket' : IDL.Null,
  'RunOut' : IDL.Null,
  'Stumped' : IDL.Null,
  'Bowled' : IDL.Null,
  'Other' : IDL.Text,
  'Caught' : IDL.Null,
});
export const Delivery = IDL.Record({
  'batsmanId' : PlayerId,
  'wicket' : IDL.Opt(WicketType),
  'runs' : IDL.Nat,
  'isNoBall' : IDL.Bool,
  'isWide' : IDL.Bool,
  'isFreeHit' : IDL.Bool,
  'isBye' : IDL.Bool,
  'isLegBye' : IDL.Bool,
  'bowlerId' : PlayerId,
});
export const BallNumber = IDL.Nat;
export const OverNumber = IDL.Nat;
export const BallByBallRecord = IDL.Record({
  'ballNumber' : BallNumber,
  'batsmanId' : PlayerId,
  'wicket' : IDL.Opt(WicketType),
  'runs' : IDL.Nat,
  'isNoBall' : IDL.Bool,
  'isWide' : IDL.Bool,
  'overNumber' : OverNumber,
  'isFreeHit' : IDL.Bool,
  'bowlerId' : PlayerId,
});
export const Innings = IDL.Record({
  'id' : IDL.Nat,
  'bowlingTeamId' : TeamId,
  'deliveries' : IDL.Vec(Delivery),
  'overs' : IDL.Nat,
  'completed' : IDL.Bool,
  'totalRuns' : IDL.Nat,
  'wicketsLost' : IDL.Nat,
  'battingTeamId' : TeamId,
});
export const Match = IDL.Record({
  'id' : MatchId,
  'isFinished' : IDL.Bool,
  'deliveries' : IDL.Vec(BallByBallRecord),
  'toss' : Toss,
  'winner' : IDL.Opt(TeamId),
  'teamAId' : TeamId,
  'teamBId' : TeamId,
  'innings' : IDL.Vec(Innings),
  'currentInnings' : IDL.Nat,
  'rules' : MatchRules,
});
export const TournamentRules = IDL.Record({
  'teamReadinessPenaltyOvers' : IDL.Nat,
  'widesNoBallBowlerChangeThreshold' : IDL.Nat,
  'finalMatches' : IDL.Nat,
  'defaultPenaltyRuns' : IDL.Nat,
  'leaguePowerplayOvers' : IDL.Nat,
  'totalMatches' : IDL.Nat,
  'slowOverRatePenaltyRuns' : IDL.Nat,
  'maxOversBowlerShortFormat' : IDL.Nat,
  'leagueOvers' : IDL.Nat,
  'freeHitApplicable' : IDL.Bool,
  'lbwApplicable' : IDL.Bool,
  'finalOvers' : IDL.Nat,
  'inningsDurationMinutes' : IDL.Nat,
  'maxBallsPerBatsmanShortFormat' : IDL.Nat,
  'knockoutMatches' : IDL.Nat,
  'finalPowerplayOvers' : IDL.Nat,
  'maxFieldersOutside30Yards' : IDL.Nat,
  'maxOversBowlerLongFormat' : IDL.Nat,
  'bouncerLimitPerOver' : IDL.Nat,
  'teamReadinessPenaltyMinutes' : IDL.Nat,
  'numTeams' : IDL.Nat,
  'semifinalMatches' : IDL.Nat,
  'leagueMatches' : IDL.Nat,
  'timeoutDurationSeconds' : IDL.Nat,
  'maxBallsPerBatsmanLongFormat' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPlayer' : IDL.Func([TeamId, IDL.Text, IDL.Nat, IDL.Bool], [PlayerId], []),
  'addTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TeamId], []),
  'createMatch' : IDL.Func([TeamId, TeamId, MatchRules, Toss], [MatchId], []),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getDeliveriesByInnings' : IDL.Func(
      [MatchId, InningsId],
      [IDL.Vec(Delivery)],
      ['query'],
    ),
  'getMatch' : IDL.Func([MatchId], [IDL.Opt(Match)], ['query']),
  'getPlayerStats' : IDL.Func([TeamId, PlayerId], [IDL.Opt(Player)], ['query']),
  'getTeam' : IDL.Func([TeamId], [IDL.Opt(Team)], ['query']),
  'getTournamentRules' : IDL.Func([], [TournamentRules], ['query']),
  'recordDelivery' : IDL.Func([MatchId, InningsId, Delivery], [], []),
  'resetAllData' : IDL.Func([], [], []),
  'selectSquad' : IDL.Func([TeamId, IDL.Vec(PlayerId)], [], []),
  'updateMatchRules' : IDL.Func([MatchId, MatchRules], [], []),
  'updateTournamentRules' : IDL.Func([TournamentRules], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TeamId = IDL.Nat;
  const PlayerId = IDL.Nat;
  const MatchRules = IDL.Record({
    'freeHitEnabled' : IDL.Bool,
    'duckworthLewisTarget' : IDL.Opt(IDL.Nat),
    'maxOversPerBowler' : IDL.Nat,
    'oversLimit' : IDL.Nat,
    'powerplayOvers' : IDL.Vec(IDL.Nat),
  });
  const TossChoice = IDL.Variant({ 'Bat' : IDL.Null, 'Bowl' : IDL.Null });
  const Toss = IDL.Record({ 'choice' : TossChoice, 'winnerTeamId' : TeamId });
  const MatchId = IDL.Nat;
  const Player = IDL.Record({
    'id' : PlayerId,
    'battingOrder' : IDL.Nat,
    'name' : IDL.Text,
    'isBowler' : IDL.Bool,
  });
  const Team = IDL.Record({
    'id' : TeamId,
    'logo' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'squad' : IDL.Vec(PlayerId),
    'players' : IDL.Vec(Player),
  });
  const InningsId = IDL.Nat;
  const WicketType = IDL.Variant({
    'LBW' : IDL.Null,
    'HitWicket' : IDL.Null,
    'RunOut' : IDL.Null,
    'Stumped' : IDL.Null,
    'Bowled' : IDL.Null,
    'Other' : IDL.Text,
    'Caught' : IDL.Null,
  });
  const Delivery = IDL.Record({
    'batsmanId' : PlayerId,
    'wicket' : IDL.Opt(WicketType),
    'runs' : IDL.Nat,
    'isNoBall' : IDL.Bool,
    'isWide' : IDL.Bool,
    'isFreeHit' : IDL.Bool,
    'isBye' : IDL.Bool,
    'isLegBye' : IDL.Bool,
    'bowlerId' : PlayerId,
  });
  const BallNumber = IDL.Nat;
  const OverNumber = IDL.Nat;
  const BallByBallRecord = IDL.Record({
    'ballNumber' : BallNumber,
    'batsmanId' : PlayerId,
    'wicket' : IDL.Opt(WicketType),
    'runs' : IDL.Nat,
    'isNoBall' : IDL.Bool,
    'isWide' : IDL.Bool,
    'overNumber' : OverNumber,
    'isFreeHit' : IDL.Bool,
    'bowlerId' : PlayerId,
  });
  const Innings = IDL.Record({
    'id' : IDL.Nat,
    'bowlingTeamId' : TeamId,
    'deliveries' : IDL.Vec(Delivery),
    'overs' : IDL.Nat,
    'completed' : IDL.Bool,
    'totalRuns' : IDL.Nat,
    'wicketsLost' : IDL.Nat,
    'battingTeamId' : TeamId,
  });
  const Match = IDL.Record({
    'id' : MatchId,
    'isFinished' : IDL.Bool,
    'deliveries' : IDL.Vec(BallByBallRecord),
    'toss' : Toss,
    'winner' : IDL.Opt(TeamId),
    'teamAId' : TeamId,
    'teamBId' : TeamId,
    'innings' : IDL.Vec(Innings),
    'currentInnings' : IDL.Nat,
    'rules' : MatchRules,
  });
  const TournamentRules = IDL.Record({
    'teamReadinessPenaltyOvers' : IDL.Nat,
    'widesNoBallBowlerChangeThreshold' : IDL.Nat,
    'finalMatches' : IDL.Nat,
    'defaultPenaltyRuns' : IDL.Nat,
    'leaguePowerplayOvers' : IDL.Nat,
    'totalMatches' : IDL.Nat,
    'slowOverRatePenaltyRuns' : IDL.Nat,
    'maxOversBowlerShortFormat' : IDL.Nat,
    'leagueOvers' : IDL.Nat,
    'freeHitApplicable' : IDL.Bool,
    'lbwApplicable' : IDL.Bool,
    'finalOvers' : IDL.Nat,
    'inningsDurationMinutes' : IDL.Nat,
    'maxBallsPerBatsmanShortFormat' : IDL.Nat,
    'knockoutMatches' : IDL.Nat,
    'finalPowerplayOvers' : IDL.Nat,
    'maxFieldersOutside30Yards' : IDL.Nat,
    'maxOversBowlerLongFormat' : IDL.Nat,
    'bouncerLimitPerOver' : IDL.Nat,
    'teamReadinessPenaltyMinutes' : IDL.Nat,
    'numTeams' : IDL.Nat,
    'semifinalMatches' : IDL.Nat,
    'leagueMatches' : IDL.Nat,
    'timeoutDurationSeconds' : IDL.Nat,
    'maxBallsPerBatsmanLongFormat' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPlayer' : IDL.Func(
        [TeamId, IDL.Text, IDL.Nat, IDL.Bool],
        [PlayerId],
        [],
      ),
    'addTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TeamId], []),
    'createMatch' : IDL.Func([TeamId, TeamId, MatchRules, Toss], [MatchId], []),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getDeliveriesByInnings' : IDL.Func(
        [MatchId, InningsId],
        [IDL.Vec(Delivery)],
        ['query'],
      ),
    'getMatch' : IDL.Func([MatchId], [IDL.Opt(Match)], ['query']),
    'getPlayerStats' : IDL.Func(
        [TeamId, PlayerId],
        [IDL.Opt(Player)],
        ['query'],
      ),
    'getTeam' : IDL.Func([TeamId], [IDL.Opt(Team)], ['query']),
    'getTournamentRules' : IDL.Func([], [TournamentRules], ['query']),
    'recordDelivery' : IDL.Func([MatchId, InningsId, Delivery], [], []),
    'resetAllData' : IDL.Func([], [], []),
    'selectSquad' : IDL.Func([TeamId, IDL.Vec(PlayerId)], [], []),
    'updateMatchRules' : IDL.Func([MatchId, MatchRules], [], []),
    'updateTournamentRules' : IDL.Func([TournamentRules], [], []),
  });
};

export const init = ({ IDL }) => { return []; };