/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BallByBallRecord {
  'ballNumber' : BallNumber,
  'batsmanId' : PlayerId,
  'wicket' : [] | [WicketType],
  'runs' : bigint,
  'isNoBall' : boolean,
  'isWide' : boolean,
  'overNumber' : OverNumber,
  'isFreeHit' : boolean,
  'bowlerId' : PlayerId,
}
export type BallNumber = bigint;
export interface Delivery {
  'batsmanId' : PlayerId,
  'wicket' : [] | [WicketType],
  'runs' : bigint,
  'isNoBall' : boolean,
  'isWide' : boolean,
  'isFreeHit' : boolean,
  'isBye' : boolean,
  'isLegBye' : boolean,
  'bowlerId' : PlayerId,
}
export interface Innings {
  'id' : bigint,
  'bowlingTeamId' : TeamId,
  'deliveries' : Array<Delivery>,
  'overs' : bigint,
  'completed' : boolean,
  'totalRuns' : bigint,
  'wicketsLost' : bigint,
  'battingTeamId' : TeamId,
}
export type InningsId = bigint;
export interface Match {
  'id' : MatchId,
  'isFinished' : boolean,
  'deliveries' : Array<BallByBallRecord>,
  'toss' : Toss,
  'winner' : [] | [TeamId],
  'teamAId' : TeamId,
  'teamBId' : TeamId,
  'innings' : Array<Innings>,
  'currentInnings' : bigint,
  'rules' : MatchRules,
}
export type MatchId = bigint;
export interface MatchRules {
  'freeHitEnabled' : boolean,
  'duckworthLewisTarget' : [] | [bigint],
  'maxOversPerBowler' : bigint,
  'oversLimit' : bigint,
  'powerplayOvers' : Array<bigint>,
}
export type OverNumber = bigint;
export interface Player {
  'id' : PlayerId,
  'battingOrder' : bigint,
  'name' : string,
  'isBowler' : boolean,
}
export type PlayerId = bigint;
export interface Team {
  'id' : TeamId,
  'logo' : string,
  'name' : string,
  'color' : string,
  'squad' : Array<PlayerId>,
  'players' : Array<Player>,
}
export type TeamId = bigint;
export interface Toss { 'choice' : TossChoice, 'winnerTeamId' : TeamId }
export type TossChoice = { 'Bat' : null } |
  { 'Bowl' : null };
export interface TournamentRules {
  'teamReadinessPenaltyOvers' : bigint,
  'widesNoBallBowlerChangeThreshold' : bigint,
  'finalMatches' : bigint,
  'defaultPenaltyRuns' : bigint,
  'leaguePowerplayOvers' : bigint,
  'totalMatches' : bigint,
  'slowOverRatePenaltyRuns' : bigint,
  'maxOversBowlerShortFormat' : bigint,
  'leagueOvers' : bigint,
  'freeHitApplicable' : boolean,
  'lbwApplicable' : boolean,
  'finalOvers' : bigint,
  'inningsDurationMinutes' : bigint,
  'maxBallsPerBatsmanShortFormat' : bigint,
  'knockoutMatches' : bigint,
  'finalPowerplayOvers' : bigint,
  'maxFieldersOutside30Yards' : bigint,
  'maxOversBowlerLongFormat' : bigint,
  'bouncerLimitPerOver' : bigint,
  'teamReadinessPenaltyMinutes' : bigint,
  'numTeams' : bigint,
  'semifinalMatches' : bigint,
  'leagueMatches' : bigint,
  'timeoutDurationSeconds' : bigint,
  'maxBallsPerBatsmanLongFormat' : bigint,
}
export type WicketType = { 'LBW' : null } |
  { 'HitWicket' : null } |
  { 'RunOut' : null } |
  { 'Stumped' : null } |
  { 'Bowled' : null } |
  { 'Other' : string } |
  { 'Caught' : null };
export interface _SERVICE {
  'addPlayer' : ActorMethod<[TeamId, string, bigint, boolean], PlayerId>,
  'addTeam' : ActorMethod<[string, string, string], TeamId>,
  'createMatch' : ActorMethod<[TeamId, TeamId, MatchRules, Toss], MatchId>,
  'getAllTeams' : ActorMethod<[], Array<Team>>,
  'getDeliveriesByInnings' : ActorMethod<[MatchId, InningsId], Array<Delivery>>,
  'getMatch' : ActorMethod<[MatchId], [] | [Match]>,
  'getPlayerStats' : ActorMethod<[TeamId, PlayerId], [] | [Player]>,
  'getTeam' : ActorMethod<[TeamId], [] | [Team]>,
  'getTournamentRules' : ActorMethod<[], TournamentRules>,
  'recordDelivery' : ActorMethod<[MatchId, InningsId, Delivery], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'selectSquad' : ActorMethod<[TeamId, Array<PlayerId>], undefined>,
  'updateMatchRules' : ActorMethod<[MatchId, MatchRules], undefined>,
  'updateTournamentRules' : ActorMethod<[TournamentRules], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];